ReactTooltip/react-tooltip

- __tests__/index-test.js
- dist/react-tooltip.js
- example/src/react-tooltip.js
- src/js/index.jsx
> fixed classnames require call

- src/js/index.jsx
When tooltip contains child elements, the mousenter event get triggered on the children and causes the tooltip to reappear with no content. The issue can be solved simply replacing mouseover with mouseenter.
> Fix bug with mouse hover triggerring on tooltip children

- example/src/index.js
Since the expression is evaluated the curly brackets would literally mean that a variable is expected with the name `top` (for example). This was breaking my app.
> Change curly brackets to quotes (single)

- dist/react-tooltip.js
- example/src/react-tooltip.js
- src/js/index.jsx
- src/scss/style.scss
Thanks for this great React lib!
> Adding support for server-side rendering

- dist/react-tooltip.js
- example/src/react-tooltip.js
- src/js/index.jsx
I removed document.querySelector and used React.findDOMNode(this) instead. This allows us to cleanup the code a bit. It should also be a bit more efficient since we are not querying the DOM as much.
> remove querySelector and use findDOMNode instead

- src/js/index.jsx
It's unnecessary to enforce the browser to calculate the rectangle data twice.
> avoid getBoundingClientRect() to be called twice

- src/index.js
It seems like in IE an exception "Object doesn't support this action" is thrown, when using the hide and rebuild functions. This is due to the fact that IE didn't have a custom Event constructor before Edge.
For more information:
http://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-ev
ent-constructor-doesnt-work
> Fixes IE's lacking event constructor

- src/index.js
I've implemented a more thorough handling for tooltips going outside of the window. The problem occurs in both float or solid mode when updating the place of the tooltip will also put it outside the window, this can happen with items (like icons) placed in a corner of the screen.
This code will only update the place of the tooltip if updating it will not put the tooltip outside in anyway. In most cases this should still fix the positioning, but for the rare cases that it doesnt it will simply allow the tooltip to go outside of the window rather than erroring with Maximum call stack size exceeded.
I've re-enabled the functionality for solid since this should always work.
> better fix for Maximum call stack size exceeded

- dist/react-tooltip.js
- src/index.js
else it will throw an error, that you can't setState of an unmounted component
> clearing delayShowLoop-Timeout when component will unmount

- dist/react-tooltip.js
- package.json
- src/index.js
This caused an exception when the tooltip was removed from the dom
before it was scheduled to show up.
> Clear timeout when unmounting.

- index.js
`index.js` was introduced in 502361992, and it imports the minified distribution build by default. This causes two problems:
1. It necessitates the addition of special workarounds to get the unminified build in development.
2. It causes webpack to break if users have the `noParse` option set for minified libraries, say with a pattern that matches `*.min.js.`. This option greatly enhances performance for webpack builds as it doesn't unpack and repack minified libraries, but it has a hard constraint that the unprocessed file **NOT** use `require()`.
Requiring the unminified build by default lets downstream tools handle bundling and minification in production, instead of forcing it by default.
> Require the non-minified dist build in index

- package.json
This will get rid of the nag message for npm v3 users and will allow npm v2 users on React 15 to continue using react-tooltip.
> Update peer dependencies to support react / react-dom >= 15.0.0

- src/index.js
I had a scenario where the tooltip needed to be triggered on click. However, the trigger element is contained within a parent component that needed to handle the trigger click event as well. Unfortunately, the tooltip checkStatus method stopped click propagation in order to add a handler for outside click events that will close the tooltip.
I tried using a custom event to activate the tooltip on trigger click. This almost worked as the click event was propagating but unfortunately the event was bubbling _after_ the checkStatus outside handler was registered, so the tooltip was being hidden immediately.
The change I ultimately ended up making was to introduce a new prop to set the propagation mode to capture instead of bubble. This effectively disableds the e.stopPropagation call in …
> Added ability to change event propagation mode from default "bubble" to "capture"

- src/index.js
When using data-html attribute, this value was assigned to the html state attribute without ensuring the bool type, so it was being assigned as a string "true" or "false".
Later, this value was accessed with the code:
`if (html) {`
this was evaluating always to true and causing the content to not being encoded.
Applied code to ensure bool value, similar to the code applied for the data-border attribute.
> Ensure data-html is converted to bool type

- example/index.html
Thanks for this repo! It's great.
I kept seeing this in my tabs, and I'd get confused:
Now, the page should have a real title. Thanks again 🌟
> Update page <title> for example page

- README.md
- Correct 2 typos in the README file, lines _44_ and _56_
> Correct Typos in README.md

- src/index.js
Problem:
A tooltip should show content, wich changes over time. E.g. show time until any event.
Solution:
Pass a function to tooltip,  which will be called on showing the component. This function will return needed content, that will be rendered instead of children.
> Add possibility to recalculate content on show tooltip

- bower.json
Hey, I noticed a mistake in my earlier PR about adding a bower.json (https://github.com/wwayne/react-tooltip/pull/179): `react-dom` is not a proper Bower dependency and the `react` package instead comes with `react-dom` properly configured in its `main`: https://github.com/reactjs/react-bower/blob/master/bower.json#L3
Sorry about the confusion, but here a fix PR.
> Remove react-dom from Bower dependencies

- example/src/index.js
- src/utils/getPosition.js
Hi,
I added some transforms to the examples as a quick way to see it's working. When calculating the tooltip position, the parent of the node should be taken as an offset, and not the target. 
This is not a complete solution, because the node can be within multiple chain-of-parents with transforms (which have to be accumulated), but at least now if the target is inside a parent with transform the tooltip is in the right position.
> Use node parent when calculating offset

- src/decorators/staticMethods.js
For IE create new Event object and set details separately because initEvent doesn't support this and we expect lately to have detail property on event object.
> Fix fire of global show event for IE

- src/index.js
Hi,
We replaced Object.keys(...) by Object.getOwnPropertyNames(...) because it's safer and has same browser support. 
It's safer because it will only retrieves index of the NodeList, and not methods. it is no longer needed to filter the output.
We did this because we encountered a problem in regard with this.
Best regards,
Gauthier JACQUES
> Replaced Object.keys(...) by Object.getOwnPropertyNames(...)

- src/decorators/getEffect.js
- src/index.js
The following text assumes that reader has read description of issue #246.
At first, I've just added `this.cleanTimer()` in `showTooltip` method.
Problem described in #246 has completely gone. 
But it's reasonable to ask: why behavior is different after `ReactTooltip.rebuild()`?
It was caused by invalid effect detection in `bindListeners` method. 
I think, this should be considered as a bug:
In the example above, there are one `<ReactTooltip />` component with default setup, both buttons SampleText(1|2) attached to this `ReactTooltip`, `data-effect` of the second button has been set to `solid`.
I haven't get an idea why `isCapture` is implemented as decorator, but I've followed the same way and have added `getEffect` decorator. I wonder what you think about it.
Test stand still available …
> Fix delayHide issue #246

- README.md
- example/src/index.js
- src/index.js
Solution for https://github.com/wwayne/react-tooltip/issues/242
I chose `className` as the name of the prop to match the convention of how CSS classes are specified on React components. It is also necessary to accept `className` for compatibility with the library [styled-components](https://github.com/styled-components/).
I did not remove the ability to call the prop `class`, but I updated the documentation and examples to prefer `className`. Let me know if you want me to add back references to `class`!
> Add support for className prop

- src/index.js
Related to issue #256 
Hope this PR would fix it once and for all.
Thanks @LeoIannacone for his diagnostics and issue report.
Thanks @tasiek for his extremely helpful diagnostics and feedback about my patch.
Thanks to @gauthierj for his important feedback, I'm glad that this approach OK for him.
Thanks everyone who has faced this issue and test this fix to make sure problem it gone.
```js
npm install 'huumanoid/react-tooltip#fix-undefined-is-not-a-function'
```
Discuss:
Should this library directly depend on `fbjs`? `react-dom` is already depends on `fbjs`.
> Fix NodeList to Array convertion

- src/index.js
it's a rare case, but if `data-tip` contains backslash, `getTargetArray` or more specifically `querySelectorAll` won't find the element
> escape backslash in getTargetArray method

- src/decorators/trackRemoval.js
- src/index.js
> Make MutationObserver-based removal tracking

- package.json
- src/index.js
In response to warnings appearing when using React 15.5+
> Use prop-types package instead of React.PropTypes

- src/index.js
If getContent returns '', the tooltip should hide. A missing
argument caused this not to work for dynamic content.
> fix(index.js): add missing argument so tooltip hides.

- src/index.js
As in title.
It will lower it's specificity to minimum. So no !important will be needed.
> insert css as first to allow easy css styling without important

- src/index.js
Deleting this one statement fixes the issue where tooltips won't show when mousing over to adjacent elements. Referenced in [#235](https://github.com/wwayne/react-tooltip/issues/235). 
Fixes #235
> Fix issue where tooltip won't show for adjacent elements.

- README.md
- example/src/index.js
- src/index.js
Hi, for a specific use case I needed to compute the tip content at runtime based on the data-tip's attribute value, so here we go.
PS :  I may have interests in maintaining the project 😉
> Compute or enrich tip content

- src/utils/getPosition.js
We now check different tooltip orientations to make sure the best one is chosen. There are 2 cases that lead to reorientation:
1.  If the desired orientation (`desiredPlace`) is completely inside the client window, and the current orientation (`place`) is different from the desired one (then **reorient to the desired orientation**)
2.  If neither the desired orientation (`desiredPlace`) nor the current one (`place`) is inside the client window, but there are other orientations that are (then **reorient to an arbitrary orientation that is inside**)
All other cases will keep the orientation as it was before.
Fixes #371
> fix(positioning): make sure tooltip is oriented correctly when close to edge

- CHANGELOG.md
- example/src/index.js
Replaced occurrences of "tootlip" with "tooltip".
> Fixes Typos

- package.json
- src/index.js
- yarn.lock
This PR will sanitize the HTML to prevent XSS attacks
> fix(tooltip): sanitize HTML to prevent XSS

- src/index.js
This component occuers exception from v3.8.1 .
In IE11 and Edge, mouse move event is trigger before mouse enter.
So, when placeholder is exist, `updateTooltip` makes error.
(See example's `Advance features` on the browser)
I think it is resolved by correct initialization.
How about this?
Regard.
> fix(index.js): fix state initialization

- src/index.js
This adds support for passing options into sanitizeHtml.  
Now the user can specify which HTML attributes can be passed into the text of the tooltip as defined here: https://www.npmjs.com/package/sanitize-html.
This was necessary because I am passing HTML into the tooltip text and I wanted more freedom to format the text as I pleased.
> added support for passing options to sanitizeHtml

- README.md
This updates the demo url in the readme from http://wwayne.com/react-tooltip to https://react-tooltip.netlify.com.
fix #450
> docs(README.md): Updates demo url

- src/index.js
'matches' function is not supported in older versions of firefox and currently this component only have a workaround implemented for old versions of internet explorer. I'm expanding that in order to support old versions of firefox as well.
> Support for older versions of firefox

- example/src/index.js
Based on comments, this will fix https://github.com/wwayne/react-tooltip/issues/306
> doc(example): expand SVG example to include elements

- README.md
- src/index.js
Originally contributed by cjzcpsyx (Jianzhong Chen),
add docs and reformat commit message.
Superceeds #445 
CC @cjzcpsyx
> fix(event): expose the original event to `afterShow` and `afterHide`

- README.md
- example/src/index.js
- src/index.js
- src/index.scss
Addresses issue: #417 
Add boolean clickable prop that allows tooltip to respond to mouse (or touch) events.
> Feat(clickable-prop): add clickable prop to enable pointer events

- README.md
- example/src/index.js
- src/index.js
Addresses issue: #430 
Replacing findDOMNode and string ref usage with callback refs so code run in StrictMode doesn't give warnings.
> Refactor(findDOMNode, string ref): replace deprecated findDOMNode and string ref

- src/index.js
React has deprecated the use of componentWillReceivedProps, the static method
getDerivedStateFromProps should be used.
> fix(index.js): Replaced the deprecated `componentWillPeceiveProps`.

- README.md
- example/src/index.js
- src/index.js
In border cases current algorithm for getting position, when tooltip is too long, will display it in invisible area of the window, to tip will be partially visible. This can be prevented by Math.min/max body.clientWidth/Height and current { left, top } positions. Such extension can not break any existing behaviour since it is just an optional property.
> feat(overridePosition): Add "overridePosition" property to handle border cases and customize position

- src/index.js
Add new param `options` to `hideTooltip()` and update `addScrollListener()`
to set `options` to `{ isScroll: true }`, so `hideTooltip()` can set
`delayHide` to `0` if `isScroll` is `true`
fix #474
> fix(src/index.js): Overwrite `delayHide` on scroll

- src/index.js
Fix hydrate issue
```javascript
Warning: Prop className did not match. Server: "__react_component_tooltip place-top type-dark" Client: "__react_component_tooltip place-top type-dark "
```
[Hydrate documentation](https://reactjs.org/docs/react-dom.html#hydrate).
> fix(wrapper): consistent classname for ssr hydrate

- src/decorators/bodyMode.js
- src/decorators/customEvent.js
- src/index.js
This PR related to feature request #137.
This feature is very suitable for me too, so I've tried to implement
it as safe as possible.
In the DOM event object, there are three properties which I think are
interesting for this feature:
1. `currentTarget` - when listener is attached to the `<body>` element,
the `currentTarget` is equals to the `<body>`. That's why it's
inappropriate to call methods like `showTooltip` with such an event
object given.
2. `target` - this is the element which raised the event.
3. `path` - this is an actual path of the event's bubbling flow. We could
traverse `path` to find the element with `[data-tip]` set, even if the
`target` of the event doesn't have the `data-tip` attribute.
There are several goals that I pursued:
1. Don't change the existing code as much as …
> Feature: listen body events

- README.md
> BREAKING CHANGE: Updating readme for demo

- src/index.js
The overridePosition argument was missing, so I added it
Now, In the example, as shown in the image below, NaN is generated as position.
Temporarily added console.log [here](https://github.com/wwayne/react-tooltip/blob/master/example/src/App.js#L772) for confirmation
> fix: providing currentTarget in overridePosition

- src/decorators/staticMethods.js
switches details to be included in the CustomEvent.initCustomEvent constructor
fix #498
See references here:
- https://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work
- https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ff975987(v%3Dvs.85)
> fix: fix ie edge CustomEvent bug

- src/decorators/staticMethods.js
fixing currentTarget for static method global show (in IE)
After making a partial fix last night for IE edge, this popped up in my error logs...
```
Unable to get property 'target' of undefined or null reference
./node_modules/react-tooltip/dist/index.es.js in t.prototype.globalShow at line 1385:1
target.prototype.globalShow = function (event) {
if (this.mount) {
// Create a fake event, specific show will limit the type to `solid`
// only `float` type cares e.clientX e.clientY
var e = {
currentTarget: event.detail.target
};
this.showTooltip(e, true);
}
};
```
So this PR has a simple fix to prevent the error.
> fix(src/decorators/staticMethods.js): fixing another IE event bug

- README.md
- contributing.md
- react-tooltip.d.ts
"re #568"
Adding typescript type defs to the repo
> feat: adding typescript type defs

- src/index.js
I don't believe the `watchWindow` prop is in use anymore.
> minor clean up of stale props

- rollup.config.js
prop-types and uuid are currently marked as "dependencies" but are also bundled by rollup.
This PR proposes to configure them as "external" to avoid bundling them.
> Mark prop-types and uuid as external to avoid bundling them

- src/index.js
When passing the `uuid` prop ReactTooltip will not generate one itself so you can have a predictable
ID when using SSR strategies"
fix #580
> fix: made it possible to pass uuid instead of generating one internally

- src/index.js
Fix for issue: #533
This patch applied on top of `v3.10.1` works fine in the `make dev` test except for the test scrolling test, which appears to work as it does in master. With a slight tweak, this patch can be applied on master.
@aronhelser Can we get a release with this patch applied to `v3.10.0`, or if not, then `v3.10.1`?
Details on the test scrolling test: The left example should hide the tooltip when scrolling. This happens on the first time, but moving the mouse slightly makes the tooltip reappear, and it does not hide again when scrolling again. This is also how it behaves without this PR's patch.
> fix: Release event listeners

- src/utils/getPosition.js
Parent elements with property will-change: transform change the containing block, we have to account
for that when calculating the tooltip position. Reference:
https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_Block
> fix(getposition): properly determine parents with will-change: transform

- README.md
* Add a note about dynamic rebinding of tooltips to capture lost event listeners as discussed in #469
* fix markdown lint violations.
> docs(readme): add tip on rebuild for dynamic content relates to #469

- README.md
Hello.
Your readme currently recommends people use `sanitize-html-react` to sanitize HTML.
This library is outdated and vulnerable to XSS.
Here is a full write up on my website:
https://mobeigi.com/blog/security/xss/sanitize-html-react-vulnerability/
Instead, I propose we recommend `sanitize-html` instead which is actively maintained and what `sanitize-html-react` was originally forked off four years ago.
Thanks.
> docs(readme): Avoid recommending sanitize-html-react

- rollup.config.js
- src/index.js
> fix: add styles for shadow dom

- src/index.js
- yarn.lock
Change style injection root to evaluated parent node, that should equal to nearest shadow root host,
otherwise use head
fix #665
> fix(style injection): change style injection default root

- src/index.js
As continue of [previous PR](https://github.com/wwayne/react-tooltip/issues/665) and fix for #650.
Previous way doesn't work correct for tooltips without related target elements :slightly_frowning_face:
> fix(styles): change style injection way

- src/index.js
Currently, `delayShow` (or `data-delay-show`) is enforced anytime `updateTooltip` is called, whether the tooltip was already shown or not. 
This results in particularly undesirable behavior when using `delayUpdate` and `delayShow` in conjunction, because after the delayed update occurs, the position of the tooltip is not updated until an additional `delayShow` timeout completes. The undesirable behavior can be seen on the [library's demo page](https://wwayne.github.io/react-tooltip/) under the heading *Demonstrate using mouse in tooltip*.
Notice how the contents of each tooltip are updated briefly before the tooltip is repositioned.
This change makes it so `delayShow` will only be enforced if the tooltip is not currently being shown.
A more conservative alternative might be to only not …
> fix: do not delay show if tooltip is already shown

- src/index.js
Fixing the following exceptions:
```
HierarchyRequestError: The operation would yield an incorrect node tree.
at DocumentImpl.appendChild (node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:380:13)
at ReactTooltip.injectStyles (node_modules/react-tooltip/dist/index.js:1203:17)
at ReactTooltip.componentDidMount (node_modules/react-tooltip/src/index.js:149:10)
at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:19847:22)
at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:22834:7)
at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
Error: Uncaught …
```
> fix(src/index.js): Fix exception when testing with Jest

- src/index.js
Add accessibility support for displaying tooltips when tabbing over an element when it receives focus.
More reading:
https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html
"Custom tooltips, sub-menus, and other nonmodal popups that display on hover and focus are examples of additional content covered by this criterion."
https://www.digitala11y.com/tooltip-role/
"The tooltip typically becomes visible in response to a mouse hover, or after the owning element receives keyboard focus. In each of these cases, authors SHOULD display the tooltip after a short delay."
I added a tabIndex to the example (not in this commit) to show a working example of tabbing and displaying tooltips:
> fix(src/index.js): add accessibility support for tabbing

- src/index.js
Fixes hiding tooltip when tabbing out of element. 
References this previous commit (Thanks @muhammadtarek for catching this) 
https://github.com/wwayne/react-tooltip/pull/695#discussion_r626010845
> fix(src/index.js): hide tooltip if blurred (tabbed out)

- README.md
Adding a note and example regarding using `data-tip` with JSX to Readme.
It took me quite some trial and error until I finally found issue #329.
Also JSX gets more and more common and it seemed there was a fair bit of "traffic" in that issue so it's probably worth adding to the Readme.
> Added note and example about JSX to Readme

- src/index.js
Fix incorrect color scheme when use type != "dark" at first render
Same with effect different from "float"
Fix #731
> fix: effect and type not properly applied at first render

- src/index.js
`afterShow` was called in the callback of a `setState`, but in the same callback `updatePosition` was also called which did another `setState`. Due to the asynchronous nature of setState that means that `afterShow` did not actually see the actual updated state. This fixes it by forwarding/moving the callback into the innermost `setState` callback. It is a bit annoying/nested but works. Suggestions welcome. Moving to hooks might be the appropriate cleanup, but that would be a somewhat larger task.
Thanks!
> fix(aftershow): call afterShow only after state has fully updated

- src/index.js
When a large number of tooltips are mounted, there is an excessive amount of unnecessary `clearTimeout()` and `clearInterval()` calls being made, which cause very slow re-renders. In our case, this PR alone shaved off much the re-render time of one particularly expensive re-render (850ms to 472ms).
> fix: performance issue caused by excessive use of clearTimeout/Interval

- src/index.js
Fix new problem with error 'Its instance type 'ReactTooltip' is not a valid JSX element.' and 'Type 'React.ReactNode' is not assignable to type 'import("/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode'.'
> fix: Its instance type 'ReactTooltip' is not a valid JSX element.

- src/index.js
Fixes an issue where the tooltip will not hide after hover.
In React 18 StrictMode, components may mount and unmount more than once
See here https://github.com/reactwg/react-18/discussions/19
Closes #754
> fix(react18): tip not hiding with React 18 StrictMode enabled

- .github/workflows/release.yaml
- example/package.json
- package.json
- yarn.lock
* fix: remove github pages deploy from the pipeline as we use a branch instead
* rollback: revert the upgrade in `uuid` package as it was breaking the examples page build (as we use old packages)
No new release required for that as the plugin is correctly working with the uuid upgraded, we just need upgrade our example folder packages before restore the uuid upgraded.
> fix: remove github pages deploy from pipeline as we use branch instead [skip ci]

- src/components/Tooltip/Tooltip.tsx
- src/components/TooltipController/TooltipController.tsx
> Fix anchor element selector to support usage of `React.useId()`

- src/components/TooltipProvider/TooltipProviderTypes.d.ts
`ReactNode` is less strict than `ReactElement`, allowing for more flexibility when using the `<TooltipWrapper />`.
See https://stackoverflow.com/a/58123882 for details
> Use `ReactNode` for wrapper children type instead of `ReactElement`

- .github/workflows/stale.yml
This should be fine since we're actively maintaining the repo. 
In the future we might want to disable auto-closing the issues.
> Add `stale` GitHub action

- package.json
Closes #869 
- Add module entry for esm in package.json
See https://rollupjs.org/guide/en/#publishing-es-modules:
> To make sure your ES modules are immediately usable by tools that work
> with CommonJS such as Node.js and webpack, you can use Rollup to
> compile to UMD or CommonJS format, and then point to that compiled
> version with the main property in your package.json file. If your
> package.json file also has a module field, ES-module-aware tools like
> Rollup and webpack 2+ will import the ES module version directly.
> fix: package main should be cjs format. (fixes #869)

- cli.js
- package.json
A fix for
- https://github.com/ReactTooltip/react-tooltip/issues/887
- https://github.com/ReactTooltip/react-tooltip/pull/881
> react-tooltip.cjs.min.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
> Fix package.json

- src/components/Tooltip/TooltipTypes.d.ts
- src/index.tsx
- tsconfig.json
Closes #920.
This seems like a bug in rollup. The output `.d.ts` file does not include the `floating-ui` import, probably because rollup gets confused by using the exact same name for both types.
```ts
// Not included in the output
// import type { Middleware } from '@floating-ui/dom'
export type Middleware = Middleware
```
> Fix `Middleware` type self-reference on build output

- src/components/Tooltip/Tooltip.tsx
Closes #924.
The `MutationObserver` API is supposed to be super optimized, so this should scale fine, but I still worry if there isn't a more efficient way to do this.
> Hide tooltip when anchor element is removed from the DOM

- .npmignore
- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/TooltipTypes.d.ts
- src/components/TooltipController/TooltipController.tsx
> fix: wrapper element changing after first render

- docs/docs/options.mdx
- package.json
- src/components/Tooltip/Tooltip.tsx
- src/test/__snapshots__/index.spec.js.snap
- src/test/index.spec.js
- yarn.lock
> fix: remove tooltip rendered element from DOM when is not showing

- docs/docs/upgrade-guide/changelog-v4-v5.md
> docs: fixed some typos

- src/components/Tooltip/Tooltip.tsx
- src/test/tooltip-props.spec.js
> Watch for added nodes and include in anchors list

- bundlesize.config.json
- src/App.tsx
- src/components/Tooltip/TooltipTypes.d.ts
- src/index.tsx
We don't even have it on the documentation that you can import the middlewares directly from the package.
If needed, the middlewares can be imported directly from `@floating-ui/dom`.
> Remove floating-ui exports to improve bundlesize

- README.md
- docs/docs/examples/anchor-select.mdx
- docs/docs/getting-started.mdx
- docs/docs/upgrade-guide/changelog-v4-v5.md
> Add section about `ReactTooltip.rebuild()` to the docs

- src/components/Tooltip/Tooltip.tsx
- src/test/__snapshots__/tooltip-attributes.spec.js.snap
- src/test/__snapshots__/tooltip-props.spec.js.snap
- src/test/utils.spec.js
- src/utils/compute-positions.ts
Closes #969 
Beta release for testing: `yarn add react-tooltip@5.9.1-beta.0`
> Expose tooltip placement using classes

- esbuild.config.prod.mjs
- package.json
Closes #974 
Dependencies used at runtime were moved in peer dependencies. Package.json is read in order to extract dependencies to make external.
Size changes results
| File | Before | After |
|-|-|-|
react-tooltip.cjs.js | 51K | 31K
react-tooltip.cjs.js.map | 95K | 53K
react-tooltip.cjs.min.js | 26K | 13K
react-tooltip.cjs.min.js.map | 96K | 55K
react-tooltip.css | 1.7K | 1.7K
react-tooltip.css.map | 1.7K | 1.7K
react-tooltip.esm.js | 50K | 28K
react-tooltip.esm.js.map | 95K | 52K
react-tooltip.esm.min.js | 26K | 11K
react-tooltip.esm.min.js.map | 96K | 54K
react-tooltip.iife.js | 54K | 32K
react-tooltip.iife.js.map | 95K | 52K
react-tooltip.iife.min.js | 26K | 13K
react-tooltip.iife.min.js.map | 95K | 54K
react-tooltip.min.js | 26K | 11K
react-tooltip.min.js.map | 96K | 54K
---
This PR …
> chore: make dependencies external

- src/components/Tooltip/Tooltip.tsx
> fix: update node contains conditional check on Tooltip component

- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/TooltipTypes.d.ts
- src/components/TooltipController/TooltipController.tsx
- src/components/TooltipController/TooltipControllerTypes.d.ts
Closes #993.
A down side might be that if styles is passed inline like this:
```tsx
<Tooltip
styles={{
attr: value
}}
/>
```
since the `styles` object will change on every render, the tooltip will recalculate its position on every render. 
That doesn't seem like a big deal, but is there a smart way to avoid this, besides forcing the user to wrap the object with `useMemo()` or something similar?
----
https://stackblitz.com/edit/react-ts-rtgmca
> Add `styles` and `render` as dependencies for the position calculation effect

- .github/workflows/bundlesize.yaml
- package.json
- rollup.config.prod.js
* update rollup-build to output missed normal CSS file
close #1004 
close #1002 
close #1000 
close #987
> fix: package export files

- docs/docs/examples/events.mdx
The id of the clickable example should be `my-tooltip-click` not `my-tooltip`
> Fixed the `id` in the clickable tooltip example

- README.md
- docs/docs/examples/anchor-select.mdx
- docs/docs/examples/basic-examples.mdx
- docs/docs/examples/children.mdx
- docs/docs/examples/content.mdx
- docs/docs/examples/delay.mdx
- docs/docs/examples/events.mdx
- docs/docs/examples/html.mdx
- docs/docs/examples/multiline.mdx
- docs/docs/examples/offset.mdx
- docs/docs/examples/place.mdx
- docs/docs/examples/provider-wrapper.mdx
- docs/docs/examples/render.mdx
- docs/docs/examples/state.mdx
- docs/docs/examples/styling.mdx
- docs/docs/examples/variant.mdx
- docs/docs/getting-started.mdx
- docs/docs/options.mdx
- docs/docs/troubleshooting.mdx
- docs/docs/upgrade-guide/basic-examples-v4-v5.mdx
- docs/package.json
- docs/yarn.lock
- rollup.config.prod.js
https://codesandbox.io/s/tender-lucy-rq1tsv?file=/src/App.js
Extra: fix Next.js 13 App project `cannot use client side component on server side components` by adding `use client` on react-tooltip. Tested with development and production build of Next.js
On a fresh Next.js 13 App project:
> feat: change the build to auto inject css into the page

- src/components/TooltipController/TooltipController.tsx
There is this warning for when the CSS selector is invalid in TooltipController.
It was useful for me when I troubleshooting an issue with a tooltip but it would print only `[react-tooltip] "undefined" is not a valid CSS selector`, but the issue was that the CSS selector contained a `\r\n` that made it invalid, not that it was undefined.
The warning is not printing the invalid selector when it is using the `data-tooltip-id` attribute. This PR proposes to print the `selector` variable that covers both selectors - anchor and id.
This produces the warning below (there is a line break in the selector):
---
:tada: And thanks for maintaining this package! The recent addition of the try/catch block that prints the warning means that only the tooltip breaks, not the whole page.
> feat: log invalid CSS selector with tooltip-id

- README.md
- docs/docs/examples/html.mdx
- docs/docs/troubleshooting.mdx
- rollup.config.prod.js
closes #1037
* `"use client"` removed as default included in our dist files
* Readme.md updated to be more simple.
* Troubleshooting section updated in our docs
> fix: use client removed from dist files

- docs/docs/troubleshooting.mdx
- package.json
- src/components/Tooltip/Tooltip.tsx
- src/test/__snapshots__/tooltip-attributes.spec.js.snap
- src/test/__snapshots__/tooltip-props.spec.js.snap
- src/test/__snapshots__/utils.spec.js.snap
- src/test/jest-setup.js
- src/test/utils.spec.js
- src/utils/debounce.ts
- yarn.lock
Relevant issue: https://github.com/ReactTooltip/react-tooltip/issues/1057
> Track window resize to reposition tooltip

- src/components/Tooltip/Tooltip.tsx
- src/test/__snapshots__/tooltip-attributes.spec.js.snap
- src/test/__snapshots__/tooltip-props.spec.js.snap
> `react-tooltip__show` class when tooltip is open

- docs/docusaurus.config.js
- docs/src/components/AdsContainerElement/index.tsx
- docs/src/components/AdsContainerElement/styles.css
- docs/src/components/AdsContainerElement/styles.module.css
- docs/src/theme/Footer/index.js
- docs/src/theme/TOC/index.js
* We are switching from google Ads to Carbon Ads to try improve the developer experience when reading our docs with cleaner ads
> chore: use carbon ads instead of google ads

- docs/docs/examples/styling.mdx
- docs/docs/getting-started.mdx
- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/core-styles.module.css
- src/tokens.css
Closes #1105.
Reminder to link to https://react-tooltip.com/docs/examples/styling#customizing-openingclosing-animation on release notes.
Beta version `react-tooltip@5.22.0-beta.1106.0`
> Fade-out transition when closing the tooltip

- docs/docs/options.mdx
- src/components/Tooltip/TooltipTypes.d.ts
- src/components/TooltipController/TooltipController.tsx
- src/components/TooltipController/TooltipControllerTypes.d.ts
- src/test/__snapshots__/tooltip-attributes.spec.js.snap
- src/test/tooltip-attributes.spec.js
As per the discussion here: https://github.com/ReactTooltip/react-tooltip/discussions/1129#discussioncomment-7717429
Support `data-tooltip-class-name` on anchor elements for injection into the tooltip container.
The tests doesn't look to be passing.
> Support data-tooltip-class-name on anchor elements

- src/components/Tooltip/Tooltip.tsx
Closes #1136.
Following suggestion from https://github.com/juggle/resize-observer/issues/103#issuecomment-1711148285
Beta version `react-tooltip@5.25.1-beta.1137.0`
> Use `setTimeout()` for `ResizeObserver` callback

- src/components/Tooltip/Tooltip.tsx
Closes #1141.
Beta version `react-tooltip@5.25.1-beta.1142.0`
> Fix click events behavior

- docs/docs/examples/styling.mdx
- src/components/Tooltip/Tooltip.tsx
- src/utils/css-time-to-ms.ts
Closes #1144.
Also fixes bug with `--rt-transition-closing-delay: 0`.
Beta version `react-tooltip@5.25.1-beta.1145.0`
> Add fallback for tooltip internal state handling when `onTransitionEnd` never fires

- src/components/Tooltip/Tooltip.tsx
- src/utils/debounce.ts
Closes #1144
---
There was an issue where the tooltip would stay open after the cursor
had already left the anchor element. The issue would arise if:
- there are two (or more) tooltip anchors A and B (same tooltip ID)
- mouse goes over A to show the tooltip, user waits for tooltip to show
- mouse quickly (within 50ms) leaves A, goes over B, then leaves B.
The tooltip component applies debouncing on the show and hide events in
case e.g. an anchor is simultaneously focused and mouseovered. If the
second leave event occurred while that debounce was still active, it was
never processed.
This commit fixes the issue by making the show and hide debounce
functions reset each other. For example, if the hide debounce has an
active timeout, calling the debounced show function will now reset the …
> fix: open/show debounce preventing tooltip from closing properly

- src/components/Tooltip/Tooltip.tsx
Closes #1149.
Beta version `react-tooltip@5.25.2-beta.1149.0`
> Use `pointermove` event instead of `mousemove` for `float` mode.

- src/components/Tooltip/Tooltip.tsx
When `data-tooltip-id` gets updated from `A` to `B` for the same DOM element, the `A` still continues showing the tooltip when it isn't expected. The PR fixes that, now `A` will properly untrack the tooltip when `data-tooltip-id` becomes not `A`
UPD: I see some failed tests. Looks like one test uses the outdated snapshot, the second one seems to be flaky. The same happens in `master` as well
> Fix: remove anchor when `data-tooltip-id` gets changed

- src/components/Tooltip/Tooltip.tsx
Closes #1111.
As discussed on #1111, after thinking about it, it does feel like a bug.
Beta version `react-tooltip@5.26.1-beta.1170.0`
Check the example here: https://stackblitz.com/edit/stackblitz-starters-ehdav1
The tooltip closes when interacting with an element inside the tooltip when it unmounts upon being interacted with.
Fork and update the package version to `react-tooltip@5.26.1-beta.1170.0` and it should be fixed.
> Check if target is connected before handling click outside

- src/components/TooltipController/TooltipController.tsx
> Use content from `activeAnchor` on `render()` to avoid desync from `content` prop

- src/components/Tooltip/Tooltip.tsx
- src/utils/compute-positions-types.d.ts
- src/utils/deep-equal.ts
Closes #1146.
Beta version `react-tooltip@5.26.1-beta.1169.0`
> Improve state handling of computed position

- src/components/Tooltip/Tooltip.tsx
- src/components/TooltipController/TooltipController.tsx
> Escape single quotes from `data-tooltip-id` selector
