ReactTooltip/react-tooltip

.gitignore
dist/react-tooltip.js
src/index.js

* Added Custom Event Support (on props: event)
* Fixed event lag on solid position
* Fixed target problem
* Removed stopPropagation on Events (if you add custom event to
element, it doesnt work)
* Added .idea folder to gitignore

New Feature, Fixes

---

.gitignore
dist/react-tooltip.js
src/index.js

Prop Name: watchWindow
Default: false
Values: true | false
To watch changes of window size & reposition tooltip

New Feature: watchWindow

---

src/index.js

@wwayne 
I implemented a simple logic to handle those cases I mentioned on the issue #83 
What do you think about it? any comments/suggestions?

Add logic to handle outside cases for solid tooltips #83

---

example/src/index.js

change spelling of "globle" to "global"

correct spelling error

---

src/index.js

Clear hide timeout on component unmount

---

src/index.js

Fixes: https://github.com/wwayne/react-tooltip/issues/121

Fixed "Wrong query selector for data-tip #121"

---

src/utils/getPosition.js

https://github.com/wwayne/react-tooltip/issues/16#issuecomment-232603473

Check if current element is under transform

---

README.md

For better readability and scan-nability :)

Added more syntax highlighting

---

src/decorators/isCapture.js

Remove unneeded console logs messages from master source files.

(fix) Remove console logs

---

README.md

using findDOMNode with this.refs.foo to show

Fix README show tip usage error

---

package.json
src/index.js
yarn.lock

Use sanitize-html-react instead of sanitize-html to avoid useless server side dependencies
fix #424

perf(Use sanitize-html-react instead of sanitize-html)

---

src/index.js

Use capture mode with globalEventOff

---

src/decorators/staticMethods.js
src/decorators/trackRemoval.js
src/index.js
src/utils/getTipContent.js

Corrected some spelling mistakes in code comments

docs: Spelling mistakes correction

---

src/utils/getPosition.js

Fix for issue: https://github.com/wwayne/react-tooltip/issues/527

fix(getPosition): updated getPosition to fix 'maximum update depth'

---

.gitignore
.travis.yml
contributing.md
example/package.json
example/src/App.js
package.json

Refactoring

---

README.md
example/src/App.js
package.json

Fixing broken link for github page

fix(githubPage): updating github page build in travis

---

src/index.js
yarn.lock

changing the currentEvent param in overridePosition use into src/index.js

fix(overridePosition): providing currentEvent in overridePosition

---

src/utils/getPosition.js

Remove shouldUpdatePlace check from position check
fix #574

fix(getPosition Util)

---

package.json

Adding types to `package.json` to fix issue @skyqrose had

adding types filename to package

---

.eslintrc
src/index.js

This was fixed by #622. Here is applying this fix.

Check if there is an internal ref to prevent calling getBoundingClientRect on undefined

---

package.json

https://github.com/wwayne/react-tooltip/issues/627

chore: remove node version limit

---

react-tooltip.d.ts

Role-property

---

src/index.js

Add aria hidden attribute to style tag to avoid screen readers to read its content
fix #691

fix: add aria hidden attribute to style tag

---

src/index.js

fix: #759 - Disable tooltip when disable prop changes

---

src/decorators/bodyMode.js

updated pull request to latest

feat(parent_body_mode): 535 search parents for data-tip if in body mode

---

example/src/App.js
example/src/index.css
example/src/index.scss
package.json
src/decorators/defaultStyles.js
src/decorators/styler.js
src/index.js
src/index.scss
test/index.spec.js

- Refactored the arrow implementation to use a rotated square element instead of border to enable the border-radius support.
- Added custom corners support to the tooltip and arrow.
- Updated tests to support new implementation and styling.

feat: Refactored the arrow implementation, added custom corners support

---

package.json
src/decorators/styler.js

fix: Fixed the tooltip arrow overlapping the tooltip content

fix: Fixed the tooltip arrow overlapping the tooltip content

---

react-tooltip.d.ts

fix: add padding into the ts type file

---

src/components/Tooltip/Tooltip.tsx

Hide tooltip when content is empty

---

docs/package.json
docs/yarn.lock
package.json
src/components/Tooltip/Tooltip.tsx

Fix interaction between `TooltipWrapper` and `click` event

---

CHANGELOG.md

chore: add a message into CHANGELOG.md file to explain about release notes

---

docs/package.json
docs/yarn.lock
package.json

This version is already published on NPM

chore: bump version to v5.3.3

---

src/components/Tooltip/Tooltip.tsx
src/components/TooltipProvider/TooltipProviderTypes.d.ts
src/components/TooltipProvider/TooltipWrapper.tsx
src/test/__snapshots__/index.spec.js.snap

Improve usage of `className` prop

---

README.md

https://bundlephobia.com/package/react-tooltip@5.4.0

docs: update README.md to include bundlephobia metrics

---

src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/TooltipTypes.d.ts
src/components/TooltipController/TooltipController.tsx

Closes #896.
Also slight refactoring for how `content` and `html` props are handled.

Fix data observer not subscribing correctly to anchor element

---

.github/workflows/bundlesize.yaml
.github/workflows/lint.yaml
.github/workflows/pull-request.yaml
bundlesize.config.json
package.json
rollup.config.prod.js
yarn.lock

Add bundle size check for new PRs

feat: add bundlesize check into the project

---

src/components/Tooltip/Tooltip.tsx

Use same tooltip wrapper type for arrow wrapper as well

---

.github/workflows/pull-request.yaml

Not sure how to test it without pushing the new workflow to master.
https://github.com/orgs/community/discussions/25722 (specifically [this comment](https://github.com/orgs/community/discussions/25722#discussioncomment-3248917) and [this one](https://github.com/orgs/community/discussions/25722#discussioncomment-3248921))

Don't run jobs on draft PRs

---

src/components/Tooltip/Tooltip.tsx
src/utils/use-isomorphic-layout-effect.ts

Fix `useLayoutEffect` warning with SSR

---

src/components/TooltipController/TooltipController.tsx

Parse `data-tooltip-float` correctly

---

src/components/Tooltip/Tooltip.tsx
src/test/__snapshots__/tooltip-attributes.spec.js.snap
src/test/__snapshots__/tooltip-props.spec.js.snap
src/test/tooltip-attributes.spec.js
src/test/tooltip-props.spec.js
src/utils/debounce.ts

Closes #1008
Beta version: `react-tooltip@5.10.6-beta.1009.1`

Fix debouncing on show/hide functions

---

docs/docs/getting-started.mdx

docs: fixed closing tag error in the docs

---

docs/docs/examples/styling.mdx

Fix the "Padding" example code to actually style padding

Update styling.mdx - wrong code in 'padding' example

---

src/components/Tooltip/Tooltip.tsx
yarn.lock

Closes #1042.
Beta version `react-tooltip@5.14.1-beta.1043.0`

Clear show/hide timeouts when the anchor is unmounted

---

src/components/Tooltip/Tooltip.tsx

Closes #1107.
Beta version `react-tooltip@5.21.7-beta.1110.0`

Fix anchor on DOM change

---

docs/docs/examples/styling.mdx
docs/docs/troubleshooting.mdx

Add documentation and troubleshooting on changing the tooltip opacity and border

---

README.md
docs/babel.config.js
docs/docusaurus.config.js
docs/package.json
docs/yarn.lock

This means the carbon ads and custom CSS are showing differently from the development build because we are not including custom CSS in our production build correctly.

fix: custom css was broken on docs on production build

---

src/utils/compute-positions.ts

Closes #1139.
Beta version `react-tooltip@5.25.1-beta.1140.0`

Use `fallbackAxisSideDirection` option on `flip()` middleware

---

src/components/Tooltip/Tooltip.tsx

Closes #1119.
Closes #1162.
Beta version `react-tooltip@5.26.1-beta.1168.0`

Improve `delayShow`/`delayHide` behavior
